### PR TITLE
Add support for the contents of `libretro_vulkan.h`

### PR DESCRIPTION
**Pull request by JesseTG**
This PR adds support for the contents of libretro's [`libretro_vulkan.h`](https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro_vulkan.h) header, which is exposed to cores that offer Vulkan support.

Notable facts:

- This PR does not add high-level abstractions. All changes are within `rust-libretro-sys`.
- Support is gated behind the `vulkan` feature, which is included in the `default` feature.
- If `vulkan` is enabled, [`ash`](https://crates.io/crates/ash) is included as a dependency. `ash` is a thin wrapper over Vulkan that relies on `bindgen`.
- If `vulkan` is disabled, `libretro_vulkan.h` is not processed.

### CODE REVIEW

**Comment by max-m** [comment]
I’ve rebased your commits onto the `dev` branch and squashed your fixup commits.
I also made the `vulkan` feature opt-in instead of opt-out.
You can check my changes to your PR in my [vulkan](https://github.com/max-m/rust-libretro/commits/vulkan) branch.

**Comment by JesseTG** [comment]
I made some changes to work around a CLion bug (without affecting users of other IDEs), check my branch again.

**Comment by max-m** [comment]
I’ve merged the `vulkan` branch into my `dev` branch.
I think we are in a place now where we can include the Vulkan support in the next release :)

**Comment by max-m** [comment]
I’ll close this one because the latest release comes with Vulkan support now!
I didn’t merge your commits 1:1 but made some changes here and there (squashed some commits, for example).
Thanks again :)

**Pull request closed without merging**
