### PR TITLE
Update rust-libretro-sys to support no_std

### PR DESCRIPTION
**Pull request by paulyoung**

### CODE REVIEW

**Comment by max-m** [comment]
Hey Paul, thanks! `no_std` was something I wanted to look into a while ago but forgot.
Because this shouldn’t be a breaking change I’ll probably merge this into the `master` branch later and cut a new point release.
Otherwise I would have rebased it onto the `dev` branch :)

**Comment by paulyoung** [comment]
Ah, sorry about that. I didn’t realize that there was a `dev` branch.

**Comment by paulyoung** [comment]
Happy to try and change the base branch if you prefer that.

There might be some changes on the `dev` branch that I’d like to use anyway if it’s stable enough.

**Comment by max-m** [comment]
I guess I broke GitHub by manually squashing and merging your PR (see be46a4d) :pensive:
But the `#[no_std]` support is now available in v0.3.2 and in den `dev` branch (because I consider that branch “WIP” I rebased it onto the master instead of merging the master back into it).

**Pull request closed without merging**
